pool:
  vmImage: 'ubuntu-18.04'

steps:
- task: UseDotNet@2
  inputs:
    version: '3.1.x'
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: publish
    projects: 'AvaloniaUI.Net.sln'
    arguments: '-c Release -o publish'
    modifyOutputPath: false
    zipAfterPublish: false
